// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/service.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_NATIVE   Type = 0
	Type_ERC20    Type = 1
	Type_ERC721   Type = 2
	Type_ERC1155  Type = 3
	Type_METAPLEX Type = 4
)

var Type_name = map[int32]string{
	0: "NATIVE",
	1: "ERC20",
	2: "ERC721",
	3: "ERC1155",
	4: "METAPLEX",
}

var Type_value = map[string]int32{
	"NATIVE":   0,
	"ERC20":    1,
	"ERC721":   2,
	"ERC1155":  3,
	"METAPLEX": 4,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

type MsgTransactionInfoRequest struct {
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *MsgTransactionInfoRequest) Reset()         { *m = MsgTransactionInfoRequest{} }
func (m *MsgTransactionInfoRequest) String() string { return proto.CompactTextString(m) }
func (*MsgTransactionInfoRequest) ProtoMessage()    {}
func (*MsgTransactionInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}
func (m *MsgTransactionInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransactionInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransactionInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransactionInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransactionInfoRequest.Merge(m, src)
}
func (m *MsgTransactionInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransactionInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransactionInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransactionInfoRequest proto.InternalMessageInfo

func (m *MsgTransactionInfoRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type MsgTransactionInfoResponse struct {
	// Collection address on current chain
	Collection    string `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	TokenId       string `protobuf:"bytes,2,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	TargetNetwork string `protobuf:"bytes,3,opt,name=targetNetwork,proto3" json:"targetNetwork,omitempty"`
	// Address on target chain
	Receiver  string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	TokenType Type   `protobuf:"varint,5,opt,name=tokenType,proto3,enum=Type" json:"tokenType,omitempty"`
}

func (m *MsgTransactionInfoResponse) Reset()         { *m = MsgTransactionInfoResponse{} }
func (m *MsgTransactionInfoResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransactionInfoResponse) ProtoMessage()    {}
func (*MsgTransactionInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}
func (m *MsgTransactionInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransactionInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransactionInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransactionInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransactionInfoResponse.Merge(m, src)
}
func (m *MsgTransactionInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransactionInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransactionInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransactionInfoResponse proto.InternalMessageInfo

func (m *MsgTransactionInfoResponse) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *MsgTransactionInfoResponse) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *MsgTransactionInfoResponse) GetTargetNetwork() string {
	if m != nil {
		return m.TargetNetwork
	}
	return ""
}

func (m *MsgTransactionInfoResponse) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *MsgTransactionInfoResponse) GetTokenType() Type {
	if m != nil {
		return m.TokenType
	}
	return Type_NATIVE
}

func init() {
	proto.RegisterEnum("Type", Type_name, Type_value)
	proto.RegisterType((*MsgTransactionInfoRequest)(nil), "MsgTransactionInfoRequest")
	proto.RegisterType((*MsgTransactionInfoResponse)(nil), "MsgTransactionInfoResponse")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4d, 0x4b, 0xeb, 0x40,
	0x18, 0x85, 0x33, 0x6d, 0xd2, 0x8f, 0xf7, 0x7e, 0x10, 0xe6, 0x6e, 0x72, 0x73, 0x21, 0x94, 0xde,
	0xbb, 0x28, 0x17, 0x9a, 0xd8, 0x48, 0x71, 0x5d, 0x6b, 0xd0, 0x82, 0x2d, 0x12, 0x43, 0x11, 0x77,
	0x69, 0x9c, 0xa6, 0xa1, 0x31, 0x13, 0x67, 0xc6, 0x4a, 0xff, 0x85, 0x7f, 0xc8, 0xbd, 0xcb, 0x2e,
	0x5d, 0x4a, 0xfb, 0x47, 0x24, 0x83, 0xdf, 0xd8, 0xdd, 0x7b, 0x9e, 0x33, 0x67, 0x66, 0x38, 0x2f,
	0xfc, 0xca, 0x19, 0x15, 0xd4, 0xe1, 0x84, 0x2d, 0x92, 0x88, 0xd8, 0x52, 0x35, 0x1d, 0xf8, 0x3d,
	0xe4, 0x71, 0xc0, 0xc2, 0x8c, 0x87, 0x91, 0x48, 0x68, 0x36, 0xc8, 0xa6, 0xd4, 0x27, 0x57, 0xd7,
	0x84, 0x0b, 0x8c, 0x41, 0x9d, 0x85, 0x7c, 0x66, 0xa0, 0x06, 0x6a, 0xd5, 0x7d, 0x39, 0x37, 0xef,
	0x10, 0x98, 0x5f, 0x25, 0x78, 0x4e, 0x33, 0x4e, 0xb0, 0x05, 0x10, 0xd1, 0x34, 0x25, 0xd2, 0x79,
	0x0e, 0xbe, 0x23, 0xd8, 0x80, 0xaa, 0xa0, 0x73, 0x92, 0x0d, 0x2e, 0x8c, 0x92, 0x34, 0x5f, 0x24,
	0xfe, 0x07, 0x3f, 0x44, 0xc8, 0x62, 0x22, 0x46, 0x44, 0xdc, 0x50, 0x36, 0x37, 0xca, 0xd2, 0xff,
	0x08, 0xb1, 0x09, 0x35, 0x46, 0x22, 0x92, 0x2c, 0x08, 0x33, 0x54, 0x79, 0xe0, 0x55, 0xe3, 0xbf,
	0x50, 0x97, 0x97, 0x05, 0xcb, 0x9c, 0x18, 0x5a, 0x03, 0xb5, 0x7e, 0xba, 0x9a, 0x2d, 0x96, 0x39,
	0xf1, 0xdf, 0xf8, 0xff, 0x03, 0x50, 0x0b, 0x84, 0x01, 0x2a, 0xa3, 0x5e, 0x30, 0x18, 0x7b, 0xba,
	0x82, 0xeb, 0xa0, 0x79, 0x7e, 0xdf, 0xdd, 0xd1, 0x51, 0x81, 0x3d, 0xbf, 0xbf, 0xe7, 0x76, 0xf4,
	0x12, 0xfe, 0x06, 0x55, 0xcf, 0xef, 0x77, 0x3a, 0xdd, 0xae, 0x5e, 0xc6, 0xdf, 0xa1, 0x36, 0xf4,
	0x82, 0xde, 0xc9, 0xb1, 0x77, 0xa6, 0xab, 0xee, 0x18, 0xb4, 0xd3, 0xb0, 0x78, 0x73, 0x08, 0xf8,
	0x90, 0x88, 0x4f, 0x6d, 0x60, 0xd3, 0xde, 0x5a, 0xaa, 0xf9, 0xc7, 0xde, 0x5e, 0xdf, 0xfe, 0xd1,
	0xfd, 0xda, 0x42, 0xab, 0xb5, 0x85, 0x1e, 0xd7, 0x16, 0xba, 0xdd, 0x58, 0xca, 0x6a, 0x63, 0x29,
	0x0f, 0x1b, 0x4b, 0x39, 0xb7, 0xe3, 0x44, 0xa4, 0xe1, 0xc4, 0x8e, 0xe8, 0xa5, 0xc3, 0x42, 0x96,
	0x4c, 0x97, 0x6d, 0xb9, 0xc1, 0x88, 0xa6, 0x0e, 0x2f, 0xbe, 0xd2, 0x8e, 0x59, 0x1e, 0xb5, 0xd3,
	0x64, 0xe2, 0x14, 0xc3, 0xa4, 0x22, 0xdd, 0xdd, 0xa7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xad,
	0xf5, 0xa2, 0xf6, 0x01, 0x00, 0x00,
}

func (m *MsgTransactionInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransactionInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransactionInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintService(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransactionInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransactionInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransactionInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TokenType != 0 {
		i = encodeVarintService(dAtA, i, uint64(m.TokenType))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintService(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TargetNetwork) > 0 {
		i -= len(m.TargetNetwork)
		copy(dAtA[i:], m.TargetNetwork)
		i = encodeVarintService(dAtA, i, uint64(len(m.TargetNetwork)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintService(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Collection) > 0 {
		i -= len(m.Collection)
		copy(dAtA[i:], m.Collection)
		i = encodeVarintService(dAtA, i, uint64(len(m.Collection)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintService(dAtA []byte, offset int, v uint64) int {
	offset -= sovService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgTransactionInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	return n
}

func (m *MsgTransactionInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Collection)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	l = len(m.TargetNetwork)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if m.TokenType != 0 {
		n += 1 + sovService(uint64(m.TokenType))
	}
	return n
}

func sovService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozService(x uint64) (n int) {
	return sovService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgTransactionInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransactionInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransactionInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransactionInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransactionInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransactionInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collection", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Collection = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetNetwork", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetNetwork = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenType", wireType)
			}
			m.TokenType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenType |= Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupService = fmt.Errorf("proto: unexpected end of group")
)
